export const segmentBoneMap: Record<string, string | null> = {
  pelvis: 'spine',
  torso: 'spine.001',
  femur_r: 'thigh.R',
  tibia_r: 'shin.R',
  patella_r: null,
  talus_r: null,
  calcn_r: 'foot.R',
  toes_r: 'toe.R',
  femur_l: 'thigh.L',
  tibia_l: 'shin.L',
  patella_l: null,
  talus_l: null,
  calcn_l: 'foot.L',
  toes_l: 'toe.L',
  humerus_r: 'upper_arm.R',
  ulna_r: 'forearm.R',
  radius_r: null,
  hand_r: 'hand.R',
  humerus_l: 'upper_arm.L',
  ulna_l: 'forearm.L',
  radius_l: null,
  hand_l: 'hand.L',
}
